# Generated by Django 4.2.2 on 2023-06-20 01:32

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CharField', 'CharField'), ('IntegerField', 'IntegerField'), ('FloatField', 'FloatField'), ('PhoneField', 'PhoneField'), ('GenderField', 'GenderField'), ('DateTimeField', 'DateTimeField'), ('DateOfBirth', 'DateOfBirth'), ('EmailField', 'EmailField'), ('BooleanField', 'BooleanField')], max_length=50)),
                ('nome', models.CharField(choices=[('NOME', 'Nome Completo'), ('END', 'Endereco'), ('TEL', 'Telefone'), ('CEL', 'Celular'), ('NOMEPAI', 'Nome do Pai'), ('NOMEMAE', 'Nome da Mae'), ('EMAIL', 'Email'), ('CPF', 'CPF'), ('RG', 'RG'), ('GENERO', 'Genero'), ('DATA', 'Data Nascimento'), ('IDADE', 'Idade'), ('VALOR', 'Valor do Emprestimo Pretendido'), ('TOTAL', 'Total'), ('VALORP', 'Valor do Emprestimo Pagar'), ('JUROS', 'Juros'), ('PREST', 'Prestacao'), ('SALDO', 'Saldo'), ('AMORTI', 'Amortizacao'), ('CUSTOM', 'Customizado')], max_length=50)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('opcoes_choices', models.TextField(blank=True, help_text='Informe as opções separadas por vírgula', null=True)),
                ('custom_nome', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aprovada', 'Aprovada'), ('Negada', 'Negada')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ValorCampoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
                ('campo_dinamico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propostas.campodinamico')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_campo_dinamico', to='propostas.proposta')),
            ],
        ),
        migrations.AddField(
            model_name='proposta',
            name='campos_dinamicos',
            field=models.ManyToManyField(through='propostas.ValorCampoDinamico', to='propostas.campodinamico'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('administrador', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
