# Generated by Django 4.2.2 on 2023-06-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
